name: stcae
dependencies:
  - python=3.6.4
  - tensorflow=1.10.0
  - tensorflow-gpu=1.10.0
  - hdf5
  - h5py
  - graphviz
  - pydot
  - keras=2.2.2
  - keras-gpu=2.2.2
  - matplotlib
  - pandas
  - scikit-learn
  - ffmpeg
  - numba
  - cudatoolkit=9.0
  - cudnn=7.3.1
  - jupyter
  - natsort
  - pip:
    - opencv-python>=3.3.1
    - imbalanced-learn
